---
title: "Untitled"
format: html
---

test d'un document en français

shortcode {{< figure src="https://placekitten.com/200/300" caption="Un chaton" >}}

$$
E = m \times c^2
$$ {#eq-gravity []}

avec une équation en ligne $\alpha[{x_{1}}]=1$ qui ne doit pas être modifiée

Formellement, le modèle gravitaire décrit la force d'une relation entre deux objets en fonction de leur distance et de leur masse respective. Par analogie, le modèle gravitaire consiste ici à évaluer le nombre de trajets professionnels entre deux localisations en prenant pour masses le nombre d'habitants au point de départ et le nombre d'emplois au point d'arrivée et, au dénominateur, une fonction $f$ croissante de la distance[^1]. On a ainsi, en indiçant les points de départ par $i$ et les points d'arrivée par $j$ :

[^1]: La distance peut être n'importe quelle métrique qui distingue les points de l'espace. On pense canoniquement à la distance euclidienne, mais le modèl es'accomode de distances par les réseaux de transport, de temps de parocurs pou prendre en compte des vitesses différentes par mode, par type de voies empruntées, par heure de déplacement ou encore pour comparer des modes pour lesquels la distance n'a que peu de signification (transport en commun, du fait du temps d'attente et des voies spécifiques). On peut également envisager un coût complet (intégrant à la fois le coût en temps mais aussi monétaire du mode de transport) ou encore un coût généralisé incluant le confort ou la sécurité perçue et associés au mode de transport. On peut en suivant @koenig1980, utiliser le logsum pour prendre en compte la variété des solutions pour se rendre à sa destination.

$$
T_{i,j} = \frac {N_{hab, i}\times N_{emp, j}} {f(d_{i,j})}
$$ {#eq-gravity}

Les premiers modèles gravitaires ont emprunté la fonction $f$ à la physique newtonienne ($f=d^2$), mais d'autres formulations ont depuis été proposées. Par exemple, la fonction $f=e^{d/\delta}$ intervient dans les modèles de choix discrets proposés par McFadden [@mcfadden1974d; @ben-akiva2018]. En remplaçant la distance par la notion de coût généralisé du transport, on peut relier cette forme fonctionnelle à un modèle de choix avec une fonction d'utilité aléatoire (*random utility model*). Il est également possible d'ajuster des formes fonctionnelles plus complexes en ajoutant des paramètres. Le modèle gravitaire arrive alors à reproduire plus ou moins des distributions de distances observées dans des enquêtes de mobilité.
